//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualStudioMenu.Plugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualStudioMenu.Plugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog.OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Branch name:.
        /// </summary>
        public static string InstallBranch_Label {
            get {
                return ResourceManager.GetString("InstallBranch.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install VS Branch.
        /// </summary>
        public static string InstallBranch_Title {
            get {
                return ResourceManager.GetString("InstallBranch.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _VS.
        /// </summary>
        public static string Menu_Name {
            get {
                return ResourceManager.GetString("Menu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install _Branch.
        /// </summary>
        public static string Menu_VsInstallBranch {
            get {
                return ResourceManager.GetString("Menu.VsInstallBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install Dogfood.
        /// </summary>
        public static string Menu_VsInstallDogfood {
            get {
                return ResourceManager.GetString("Menu.VsInstallDogfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run VS Installer.
        /// </summary>
        public static string Menu_VsInstaller {
            get {
                return ResourceManager.GetString("Menu.VsInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install From Web.
        /// </summary>
        public static string Menu_VsInstallFromWeb {
            get {
                return ResourceManager.GetString("Menu.VsInstallFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string Menu_VsUpdating {
            get {
                return ResourceManager.GetString("Menu.VsUpdating", resourceCulture);
            }
        }
    }
}
